apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    run: web-server
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: web-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  selector:
    matchLabels:
      run: web-server
  replicas: 1
  template:
    metadata:
      labels:
        run: web-server
    spec:
      containers:
      - name: web-server
        image: nginx:latest
        ports:
        - containerPort: 443
        - containerPort: 80
