apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    run: web-server
spec:
  containers:
  - name: web-server
    image: nginx:latest
    ports:
    - containerPort: 443
    - containerPort: 80
