apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: web-server
spec:
  replicas: 5
  selector:
    matchLabels:
      run: web-server
  template:
    metadata:
      labels:
        run: web-server
    spec:
      containers:
      - name: web-server
        image: nginx:latest
        ports:
        - containerPort: 443
        - containerPort: 80
