apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    run: web-server
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: web-server
    version: latest
#    version: "1.14"
